version: '3.5'

services:
  product_database:
    container_name: products_db
    image: postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - products_db:/data/postgres
    ports:
      - "5434:5432"
  orders_database:
    container_name: orders_db
    image: postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - orders_db:/data/postgres
    ports:
      - "5433:5432"

volumes:
  products_db:
    driver: local
  orders_db:
    driver: local