server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}