server:
  port: 8761

logging:
  level:
    org:
      springframework: DEBUG

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 20
